version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: storeuser
      MONGO_INITDB_ROOT_PASSWORD: storepassword
      MONGO_INITDB_DATABASE: storedb

    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: storeuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: storepassword
      ME_CONFIG_MONGODB_URL: mongodb://storeuser:storepassword@mongo:27017/